fixed: dtos referencing entites directly
Rasmus-Kibshede/TinyTitleTinderServer pull request #32
Opened 2023-11-17 18:54 UTC by Fladbrod

2023-11-17 19:16 UTC, Geofery approved these changes
Lavede de samme ændringer på min branch i eftermiddags 🤦🏼‍♂️😂. Du mangler at kigge på hvilke dto klasser skal have relation til andre dtoer. Men dem har jeg ændret de fleste af på min branch. 

Godt arbejde

2023-11-18 00:56 UTC, Rasmus-Kibshede requested changes

2023-11-18 00:56 UTC, Rasmus-Kibshede commented on package.json
> +    "dev": "nodemon src/index.ts --exec \"npm run format && npm run lint && ts-node\"",
run format skal ikke køres når dev scriptet køres, da eslint selv fraråder at bruge det og kan skabe konflikter. Det skal kun bruges til tilføjde som Jeff kan have, da han bruger mac

2023-11-18 13:39 UTC, Rasmus-Kibshede approved these changes

2023-11-18 13:40 UTC, merged