Tin-108-refactor-meaning
Rasmus-Kibshede/TinyTitleTinderServer pull request #36
Opened 2023-11-23 13:14 UTC by Geofery

findNamesByParentId kan nu retunere: 
Liked names
disliked names
Navne uden relation til en parent. 

I body tilføjer man
{
 "isLiked": true
}

{
 "isLiked": false
}
eller en tom body for navne uden relation. 

Har også ændret i signup response. Den sender nu et dto objekt retur med alle relationer oven i. User, parent, address, location osv.

2023-11-23 18:06 UTC, Fladbrod requested changes
Har fikset de fleste foreign keys hvis navn bliver auto genereret. Mangler kun ManyToOne relation på address og dets foreignkey som bliver sat til locationLocationId. Ved ikke endnu om løsningen findes - kigger på det senere.

2023-11-23 18:53 UTC, Rasmus-Kibshede reviewed
Det ser godt ud :) Du har været aktiv :D Der er Nogle tvivlsome REST API opbygnings conventioner, der brydes, men igen kun et skole projekt :)

Godt arbejde

2023-11-23 18:53 UTC, Rasmus-Kibshede commented on src/Controllers/nameController.ts
> +  const response = await nameService.getNamesByParentId(Number(req.params.id), req.body.isLiked);
smid isLiked i parameter istedet, da det er en GET metode. Ligesom du gør med id

2023-11-23 18:53 UTC, Rasmus-Kibshede commented on src/Controllers/definitionController.ts
> +export const getAllDefinition = async (req: Request, res: Response) => {
```suggestion
export const getAllDefinitions = async (req: Request, res: Response) => {
```

2023-11-23 18:53 UTC, Rasmus-Kibshede commented on src/Entities/Parent.ts
name: 'parent_name_suggest', burde nok navngives til name: 'parent_name_suggest_like',

2023-11-23 18:53 UTC, Rasmus-Kibshede commented on src/Services/nameService.ts
> +    response = await nameRepo.findNamesNoRelation();
```suggestion
    } else {
    response = await nameRepo.findNamesNoRelation();
    }
```

2023-11-23 18:53 UTC, Rasmus-Kibshede commented on src/routes/definitionRoute.ts
> +const definitionRoute = express.Router();
```suggestion
import { Router } from 'express';
import * as definitionController from '../Controllers/definitionController';
import { validateParamsId } from '../Utils/routeUtil';

const definitionRoute = Router();
```

2023-11-24 20:10 UTC, Rasmus-Kibshede approved these changes

2023-11-24 20:13 UTC, Fladbrod approved these changes
Stamp of approval 👍

2023-11-24 20:33 UTC, merged