Tin 87 transactions
Rasmus-Kibshede/TinyTitleTinderServer pull request #45
Opened 2023-12-03 11:40 UTC by Fladbrod

- Added work around for audit tables foreign key issue. This removes the values of the unique columns of the foreign keys in the audit tables. This is used when working in a dev "synchronized = true" environment. In production synchronized = false, we can 
```
ALTER TABLE adt_user
    DROP COLUMN fk_parent_id;

ALTER TABLE adt_user
    ADD COLUMN fk_parent_id INT;
```
To get rid of the unique constraint - and keep the foreign key values.

- Added transaction for updating liked and disliked names for a given user.
- Added index for names
- Cleanup

2023-12-03 19:06 UTC, Geofery commented on src/Entities/AuditEntities/UserADT.ts
> -    @ManyToMany(() => RoleADT, (role) => role.users, { nullable: true })
Denne her vil jeg nok beholde for at logge hvornår/hvis en user får ændret rolle på sig.

2023-12-04 10:32 UTC, Geofery commented on src/Repositories/parentRepository.ts
> +                        parentId,
Skal laves om, hvis du liker 100 navne, så vil den lave 100 inserts into I databasen. Det kommer til at crashe vores database hvis flere går ind og gør det på samme tid.

2023-12-04 10:33 UTC, Geofery requested changes
Transaction skal laves om og blot benytte sig af update parent endpoint. Transaction skal vi have implementeret på signup.

2023-12-12 12:19 UTC, Rasmus-Kibshede approved these changes

2023-12-12 12:19 UTC, Rasmus-Kibshede approved these changes

2023-12-12 12:27 UTC, merged